# Generated by Django 5.1.3 on 2024-11-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('date_of_the_event', models.DateTimeField(verbose_name='date of event')),
            ],
        ),
        migrations.CreateModel(
            name='Work_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(verbose_name='date of due')),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
