# Generated by Django 5.1.3 on 2024-11-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
