# Generated by Django 5.1.3 on 2024-11-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessapp', '0002_work_order_in_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_order',
            old_name='work_order',
            new_name='work_name',
        ),
        migrations.AlterField(
            model_name='events',
            name='date_of_the_event',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='due_date',
            field=models.DateField(),
        ),
    ]
