# Generated by Django 5.1.3 on 2024-11-28 22:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessapp', '0003_rename_work_order_work_order_work_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order',
            name='date_poster',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 28, 17, 30, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_title', models.CharField(max_length=200)),
                ('work_orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buisnessapp.work_order')),
            ],
        ),
    ]
