# Generated by Django 5.1.3 on 2024-11-28 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessapp', '0004_work_order_date_poster_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_order',
            old_name='date_poster',
            new_name='date_posted',
        ),
    ]
