# Generated by Django 5.1.3 on 2024-12-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessapp', '0008_work_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
