# Generated by Django 5.1.3 on 2024-12-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buisnessapp', '0009_events_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_order',
            name='done',
        ),
    ]
